agents:
  provider: "gcp"
  image: "family/apm-agent-android-ubuntu-2204"

steps:
  - label: "Run the release"
    key: "release"
    commands: .ci/release-wrapper.sh
    artifact_paths: "release.out"

notify:
  - slack:
      channels:
        - "#apm-agent-mobile"
