agents:
  provider: "gcp"

steps:
  - label: "Run the release"
    key: "release"
    commands: .ci/release.sh | tee release.out

  - label: "Upload the logs"
    depends_on: "release"
    commands: .ci/upload-logs.sh release.out

notify:
  - slack:
      channels:
        - "#apm-agent-mobile"
