[libraries]
androidx-lifecycle-process = "androidx.lifecycle:lifecycle-process:2.8.7"
opentelemetry-api-incubator = "io.opentelemetry:opentelemetry-api-incubator:1.46.0-alpha"

# Testing
androidx-test-core = "androidx.test:core-ktx:1.6.1"
androidx-test-rules = "androidx.test:rules:1.6.1"
androidx-test-runner = "androidx.test:runner:1.6.2"
androidx-test-ext = "androidx.test.ext:junit:1.2.1"

[bundles]
androidTest = ["androidx-test-rules", "androidx-test-runner", "androidx-test-ext", "androidx-test-core"]
