[[intro]]
== Introduction

The Elastic APM Android Agent measures the performance of your application and tracks errors.
It has a default configuration that suits most common use cases.

[float]
[[how-it-works]]
=== How does the Agent work?

The Agent is built on top of https://github.com/open-telemetry/opentelemetry-android[OpenTelemetry Android] and helps setting everything up to get your project up and running with Elastic without having to get too deep into the OpenTelemetry API to make it all work.
It also serves as an extension to provide support for Elastic-specific features, such as <<configuration-dynamic, dynamic configuration>>.

It makes sure to configure OpenTelemetry in a way that any custom Spans, as well as Logs and Metrics, created using the https://opentelemetry.io/docs/instrumentation/java/manual/[OpenTelemetry Java API], contain useful attributes that enrich the overall telemetry data.
Spans, Logs and Metrics are sent to the APM Server, where they're converted to a format suitable for Elasticsearch.
You can then use the APM app in Kibana to gain insight into latency issues and error culprits within your application.

More detailed information on how the Agent works can be found in the <<faq-how-does-it-work,FAQ>>.

[float]
[[additional-components]]
=== Additional components

APM Agents work in conjunction with the {apm-guide-ref}/index.html[APM Server], {ref}/index.html[Elasticsearch], and {kibana-ref}/index.html[Kibana].
The {apm-guide-ref}/index.html[APM Guide] provides details on how these components work together, and provides a matrix outlining {apm-guide-ref}/agent-server-compatibility.html[Agent and Server compatibility].