[[intro]]
== Introduction

The Elastic APM Android Agent automatically measures the performance of your application and tracks errors.
It has a default configuration that suits most common use cases and built-in support for popular frameworks and technologies.
The agent is built on top of https://opentelemetry.io/[OpenTelemetry], enabling you to add custom instrumentation with the
https://opentelemetry.io/docs/instrumentation/java/manual/[OpenTelemetry Java API].

[float]
[[how-it-works]]
=== How does the Agent work?

The Agent auto-instruments <<supported-technologies>> and records interesting events, like spans for outgoing HTTP requests and UI rendering processes.
To do this, it leverages the capability of the Android Gradle plugin API to instrument the bytecode of classes.
This means that for supported technologies, there are no code changes required.

Spans are grouped in transactions -- by default, one for each outgoing HTTP request or UI rendering process.
It's also possible to create custom transactions, as well as logs and metrics, with the https://opentelemetry.io/docs/instrumentation/java/manual/[OpenTelemetry Java API], which is automatically provided to the Agent's host app.
Spans, Logs and Metrics are sent to the APM Server, where they're converted to a format suitable for Elasticsearch.
You can then use the APM app in Kibana to gain insight into latency issues and error culprits within your application.

NOTE: The metrics aggregation strategy used by the agent is https://github.com/open-telemetry/opentelemetry-java/blob/976edfde504193f84d19936b97e2eb8d8cf060e2/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/AggregationTemporality.java#L15[DELTA].

More detailed information on how the Agent works can be found in the <<faq-how-does-it-work,FAQ>>.

[float]
[[additional-components]]
=== Additional components

APM Agents work in conjunction with the {apm-guide-ref}/index.html[APM Server], {ref}/index.html[Elasticsearch], and {kibana-ref}/index.html[Kibana].
The {apm-guide-ref}/index.html[APM Guide] provides details on how these components work together, and provides a matrix outlining {apm-guide-ref}/agent-server-compatibility.html[Agent and Server compatibility].