[[supported-technologies]]
== Supported technologies

The Elastic APM Android agent is built on top of https://github.com/open-telemetry/opentelemetry-android[OpenTelemetry Android] -- extending its functionality to provide an easier experience when combining OpenTelemetry with Elastic.
This section lists all supported technologies.

* <<supported-agp-versions>>
* <<supported-android-runtime-versions>>
* <<supported-languages>>

[float]
[[supported-agp-versions]]
=== Android Gradle Plugin versions

|===
|Supported versions

| >= 7.4.0
|===

[float]
[[supported-android-runtime-versions]]
=== Android runtime versions

|===
|Supported versions

| API >= 24
|===

NOTE: If your minSdk version is lower than 26, then you must add https://developer.android.com/studio/write/java8-support#library-desugaring[Java 8+ desugaring support] to your application.

[float]
[[supported-languages]]
=== Languages

The Java version is for the supported JDK, which is aligned with the JDK version supported by the Android Gradle plugin.
The Kotlin version refers to the Kotlin gradle plugin versions, also aligned with the versions supported by the Android Gradle plugin.

|===
|Language |Supported versions

|Java
|11

|Kotlin
|1.8+

|===