[[supported-technologies]]
== Supported technologies

The Elastic APM Android agent is built on top of the https://opentelemetry.io[OpenTelemetry Java SDK] -- extending its functionality while also automatically instrumenting various APIs and frameworks.
This section lists all supported technologies.

* <<supported-agp-versions>>
* <<supported-android-runtime-versions>>
* <<supported-languages>>
* <<supported-ui-frameworks>>
* <<supported-networking-frameworks>>

[float]
[[supported-agp-versions]]
=== Android Gradle Plugin versions

|===
|Supported versions

| >= 7.4.0
|===

[float]
[[supported-android-runtime-versions]]
=== Android runtime versions

|===
|Supported versions

| API >= 24
|===

NOTE: If your minSdk version is lower than 26, then you must add https://developer.android.com/studio/write/java8-support#library-desugaring[Java 8+ desugaring support] to your application.

[float]
[[supported-languages]]
=== Languages

The Java version is for the supported JDK, which is aligned with the JDK version supported by the Android Gradle plugin.
The Kotlin version refers to the Kotlin gradle plugin versions, also aligned with the versions supported by the Android Gradle plugin.

|===
|Language |Supported versions

|Java
|11

|Kotlin
|1.5+

|===

[float]
[[supported-ui-frameworks]]
=== UI frameworks

|===
|Class |Notes |Since

|https://developer.android.com/reference/android/app/Activity[Activity]
|Comes from the Android SDK
|0.1.0

|https://developer.android.com/reference/androidx/fragment/app/Fragment.html[Fragment]
|Comes from the https://developer.android.com/jetpack[Android Jetpack tools]
|0.1.0

|===

[float]
[[supported-networking-frameworks]]
=== Networking frameworks

Distributed tracing will only work if you are using one of the supported networking frameworks.

For the supported HTTP libraries, the agent automatically creates spans for outgoing HTTP requests and propagates tracing headers.
The spans are named after the schema `<method> <host>`, for example `GET elastic.co`.

|===
|Framework |Supported versions | Note | Since

|OkHttp
|3.11+
|OkHttp-managed threads and Kotlin coroutine related calls are automatically traced. Calls from tools using OkHttp (such as Retrofit) are automatically traced as well.
|0.1.0

|===