[[troubleshooting]]
== Troubleshooting

[discrete]
=== General

The agent creates logs that enable you to see what it is working on and
what might have failed at some point. You can find those in
https://developer.android.com/studio/debug/logcat[logcat], filtered by
the tag `ELASTIC_AGENT`.

For more information about the agent's internal logs, as well as how to
configure them, refer to the
xref:configuration.asciidoc#internal-logging-policy[internal logging policy]
configuration.

[discrete]
=== Connectivity to the Elastic Stack

If after following the xref:getting-started.asciidoc[getting started] guide
and configuring your Elastic Stack
xref:configuration.asciidoc#export-connectivity[endpoint parameters], you
can't see your application's data in Kibana, you can follow the
following tips to try and figure out what could be wrong.

[discrete]
==== Checking out logs

The agent prints debug logs, which can be seen in
https://developer.android.com/studio/debug/logcat[logcat], using the tag
`ELASTIC_AGENT`, where you can have a look at your endpoint
configuration parameters with a log that reads: _"Initializing
connectivity with config ++[++your endpoint configuration++]++"_. Take a
look at those and make sure that the provided configuration matches your
Elastic Stack endpoint parameters.

[discrete]
[[inspecting-network-traffic]]
==== Inspecting network traffic

You can take a look at your app's outgoing network requests via Android
Studio's
http://developer.android.com/studio/debug/network-profiler[network
inspector tool]. This tool can show you the agent's export requests,
where you can see if they were successful or not, as well as the request
body and the Elastic Stack response body for when you need more details
of the whole process. Apart from that, this tool also provides a way to
export a file with the information of all of your app's HTTP requests,
which you could share with our support team if needed.

[discrete]
==== SSL/TLS error

Sometimes the request to the Elastic Stack endpoint won't show up in the
xref:#inspecting-network-traffic[network inspector]. A common issue when
this happens is that there is an SSL/TLS error that occurs when the
agent tries to contact your Elastic Stack endpoint. This is often the
case when you work with an on-prem Elastic Stack that doesn't have
trusted CAs, for which you'd need to add custom security configurations
to your app to make the export work. Take a look at
xref:how-tos.asciidoc#how-to-configure-ssltls[how to configure SSL/TLS] for
more information.
