name: Draft CHANGELOG entries for a release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run changelog draft script
        run: ./.github/scripts/change-log/draft.sh
